const IRREGULARITY_LIMIT_TO_SEND_ALERT = 5;
const MEASURE_COUNT_LIMIT = 60;
const PERCENTUAL_DIFF_LIMIT = 20;

module.exports = {
  IRREGULARITY_LIMIT_TO_SEND_ALERT,
  MEASURE_COUNT_LIMIT,
  PERCENTUAL_DIFF_LIMIT,
};
